// packages/renderer/src/App.tsx
import { useState } from "react";
import "./App.css";
import logo from "../assets/react-logo.svg";
import ElectronVersions from "./components/ElectronVersions";
import ReactiveCounter from "./components/ReactiveCounter";
import ReactiveHash from "./components/ReactiveHash";

function App() {

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />

        <p>Hello Electron + Vite + React!</p>

        <ReactiveCounter />

        <p>
          Edit <code>packages/renderer/src/App.tsx</code> to test HMR updates.
        </p>

        <p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            React
          </a>
          {" | "}
          <a
            className="App-link"
            href="https://vitejs.dev/guide/features.html"
            target="_blank"
            rel="noopener noreferrer"
          >
            Vite
          </a>
          {" | "}
          <a
            className="App-link"
            href="https://github.com/cawa-93/vite-electron-builder"
            target="_blank"
            rel="noopener noreferrer"
          >
            vite-electron-builder
          </a>
        </p>

        <fieldset>
          <legend>Exposing Node.js API</legend>
          <ReactiveHash />
        </fieldset>

        <fieldset>
          <legend>Environment</legend>
          <ElectronVersions />
        </fieldset>
      </header>
    </div>
  );
}

export default App;

// packages/renderer/src/App.vue
<script lang="ts" setup>
import ReactiveCounter from '/@/components/ReactiveCounter.vue';
import ReactiveHash from '/@/components/ReactiveHash.vue';
import ElectronVersions from '/@/components/ElectronVersions.vue';</script>

<template>
  <img
    alt="Vite logo"
    src="../assets/logo.svg"
    width="150"
  >

  <p>
    For a guide and recipes on how to configure / customize this project,<br>
    check out the
    <a
      href="https://github.com/cawa-93/vite-electron-builder"
      target="_blank"
    >vite-electron-builder documentation</a>.
  </p>

  <fieldset>
    <legend>Test Vue Reactivity</legend>
    <reactive-counter />
  </fieldset>

  <fieldset>
    <legend>Test Node.js API</legend>
    <reactive-hash />
  </fieldset>

  <fieldset>
    <legend>Environment</legend>
    <electron-versions />
  </fieldset>

  <p>
    Edit
    <code>packages/renderer/src/App.vue</code> to test hot module replacement.
  </p>
</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin: 60px auto;
  max-width: 700px;
}
fieldset {
  margin: 2rem;
  padding: 1rem;
}
</style>
